# Generated by Django 5.0.4 on 2024-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipfile', models.BooleanField(default=False)),
                ('screenshot', models.BooleanField(default=False)),
                ('elements', models.BooleanField(default=False)),
                ('demo', models.CharField(default=False, max_length=255)),
                ('html', models.BooleanField(default=False)),
            ],
        ),
    ]
