# Generated by Django 4.2.18 on 2025-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordpres_org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('zipfile', models.URLField(blank=True, null=True)),
                ('screenshot', models.URLField(blank=True, null=True)),
                ('fivestars', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('tested', models.CharField(blank=True, max_length=255, null=True)),
                ('requires', models.CharField(blank=True, max_length=255, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('downloaded', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
