# Generated by Django 4.2.18 on 2025-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipfile', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshot', models.BooleanField(default=False)),
                ('elements', models.BooleanField(default=False)),
                ('html', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unused', models.BooleanField(default=False)),
                ('fivestars', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'db_table': 'plugin',
                'ordering': ['name'],
            },
        ),
    ]
