# Generated by Django 5.1.6 on 2025-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("vendor_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews", models.IntegerField(blank=True, null=True)),
                ("price", models.CharField(max_length=255)),
            ],
        ),
    ]
